/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Box001_Material_#32_0"]: THREE.Mesh;
  };
  materials: {
    Material_32: THREE.MeshStandardMaterial;
  };
};

export function Axe(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/axe.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Box001_Material_#32_0"].geometry}
        material={materials.Material_32}
        scale={0.5}
      />
    </group>
  );
}

useGLTF.preload("/axe.glb");
