/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ilovegm.rgm79 (https://sketchfab.com/ilovegm.rgm79)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/enhanced-action-explosion-effect-part-4930050d85044fd4b30d10aaa429d6f7
Title: Enhanced Action Explosion Effect part
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshStandardMaterial;
  };
};

export function Explosion(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/enhanced_action_explosion_effect_part.glb"
  ) as GLTFResult;
  materials["Scene_-_Root"].transparent = true; // This ensures the material respects opacity
  materials["Scene_-_Root"].opacity = 0.5;
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 1, 0]}
      />
    </group>
  );
}

useGLTF.preload("/enhanced_action_explosion_effect_part.glb");
